spring.application.name=Spring-React
server.port=9090

spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/springreact
spring.datasource.username=postgres
spring.datasource.password=Feizo@002
